github_checks:
  annotations: false

comment:
  layout: "reach, diff, flags, files"
  hide_project_coverage: true

ignore:
  - "sentinel-demo/.*"
  - "sentinel-dashboard/.*"
  - "sentinel-benchmark/.*"
  - "sentinel-transport/.*"
  - "sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/*"
