flag_management:
  default_rules:
    carryforward: true

ignore:
  - "sentinel-demo/.*"
  - "sentinel-dashboard/.*"
  - "sentinel-benchmark/.*"
  - "sentinel-transport/.*"
  - "sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/*"
