coverage:
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 50%

comment:
  layout: "reach, diff, flags, files"
  hide_project_coverage: true

ignore:
  - "sentinel-demo/.*"
  - "sentinel-dashboard/.*"
  - "sentinel-benchmark/.*"
  - "sentinel-transport/.*"
  - "sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/*"
